all: 1 2

1: 1.cpp
	clang++ 1.cpp -o 1

2: 2.cpp
	clang++ 2.cpp -o 2

3: 3.cpp
	clang++ 3.cpp -o 3

4--humans: 4--humans.cpp
	clang++ 4--humans.cpp -o 4--humans

4--ai--fotis: 4--ai--fotis.cpp
	clang++ 4--ai--fotis.cpp -o 4--ai--fotis

4--ai--bo: 4--ai--bo.cpp
	clang++ 4--ai--bo.cpp -o 4--ai--bo
