all: 1 2

1: 1.cpp
	clang++ 1.cpp -o 1

2: 2.cpp
	clang++ 2.cpp -o 2

3: 3.cpp
	clang++ 3.cpp -o 3

4--humans: 4--humans.cpp
	clang++ 4--humans.cpp -o 4--humans

4--ai--fotis: 4--ai--fotis.cpp
	clang++ 4--ai--fotis.cpp -o 4--ai--fotis

4--ai--bo: 4--ai--bo.cpp
	clang++ 4--ai--bo.cpp -o 4--ai--bo

5--humans: 5--humans.cpp
	clang++ 5--humans.cpp -o 5--humans

5--chat-gpt: 5--chat-gpt.cpp
	clang++ 5--chat-gpt.cpp -o 5--chat-gpt

6--humans: 6--humans.cpp
	clang++ 6--humans.cpp -o 6--humans

6--chat-gpt: 6--chat-gpt.cpp
	clang++ 6--chat-gpt.cpp -o 6--chat-gpt

7--humans: 7--humans.cpp
	clang++ 7--humans.cpp -o 7--humans

7--chat-gpt: 7--chat-gpt.cpp
	clang++ 7--chat-gpt.cpp -o 7--chat-gpt

8: 8.cpp
	clang++ -std=c++11 8.cpp -o 8

9--humans: 9--humans.cpp
	clang++ 9--humans.cpp -o 9--humans

9--chat-gpt: 9--chat-gpt.cpp
	clang++ 9--chat-gpt.cpp -o 9--chat-gpt

10--humans: 10--humans.cpp
	clang++ 10--humans.cpp -o 10--humans

10--chat-gpt: 10--chat-gpt.cpp
	clang++ 10--chat-gpt.cpp -o 10--chat-gpt
